spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.52.196:3306/library?serverTimezone=UTC
    username: root
    password: Sy1115!!

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
